### ISSUE TITLE
ImportError: cannot import name FileWriter

### ISSUE THREAD

**Issue by leeeeeeo** [hanzhanggit/StackGAN-Pytorch#11]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from trainer import GANTrainer
  File "/media/server009/seagate/liuhan/text2img/StackGAN-Pytorch-master/code/trainer.py", line 24, in <module>
    from tensorboard import FileWriter
ImportError: cannot import name FileWriter

@hanzhanggit 
Did I do something wrong?
Why cannot import FileWriter?
Thank you very much!

**Comment by leeeeeeo** [comment]
solved. it's caused by tensorboard version. it's ok in 1.0.0a6 ~
