### ISSUE TITLE
Work on Windows 10?

### ISSUE THREAD

**Issue by gruossomonica** [hanzhanggit/StackGAN-Pytorch#20]
Hi, I'm working on Windows 10, I get this issue:

```
DATAPATH:  ../data/coco/test/val_captions.t7
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "D:\documenti\Monica\StackGAN-Pytorch\code\trainer.py", line 243, in sample
    t_file = torchfile.load(datapath)
  File "C:\Users\Utente\venv\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\Utente\venv\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Utente\venv\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Utente\venv\lib\site-packages\torchfile.py", line 414, in read_obj
    "unknown object type / typeidx: {}".format(typeidx))
torchfile.T7ReaderException: unknown object type / typeidx: -1112529805
```

Can anyone help me? Does StackGAN-Pytorch work on Windows?

**Comment by Vrishod** [comment]
Did u resolve this? Even i am getting the same isssue

**Comment by gruossomonica** [comment]
Unfortunately no. I tested on Ubuntu, no problem in this case.

**Comment by lifebl** [comment]
> Did u resolve this? Even i am getting the same isssue

hello, have you solved the problem?
